WebUI/Controllers/BFS1/BFS1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers.BFS1
{
    public class BFS1Controller : Controller
    {
        // GET: BFS1
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebUI/Controllers/BFS2/BFS2Controller.cs
using EFBF9.Abstract;
using EFBF9.Concrete;
using EFBF9.DataSet;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using TReport.TData;
using WebUI.Infrastructure;

namespace WebUI.Controllers.BFS2
{
    [Access(LogVisit = true)]
    public class BFS2Controller : Controller
    {

        IBF9UnloadBunker unb;
        IBF9UnloadMaterial unm;

        public BFS2Controller(IBF9UnloadBunker unb, IBF9UnloadMaterial unm)
        {
            this.unb = unb;
            this.unm = unm;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UnloadMaterial()
        {
            return View();
        }

        #region Отчет о загрузке БЗУ
        /// <summary>
        /// Вызвать главную форму
        /// </summary>
        /// <returns></returns>
        public ActionResult UnloadBunker()
        {
            ViewBag.HierarchyMenu = "HOME:ADD;HOME:BFS2;HOME:BFS2Unload";
            ViewBag.dt_start = Thread.CurrentThread.CurrentCulture.Name=="en-US" ?  DateTime.Now.Date.ToString("MM/dd/yyyy 00:00") : DateTime.Now.Date.ToString("dd.MM.yyyy 00:00");
            ViewBag.dt_stop = Thread.CurrentThread.CurrentCulture.Name=="en-US" ? DateTime.Now.AddDays(1).Date.AddSeconds(-1).ToString("MM/dd/yyyy 23:59"): DateTime.Now.AddDays(1).Date.AddSeconds(-1).ToString("dd.MM.yyyy 23:59");
            return View();
        }
        /// <summary>
        /// Сформировать ajax отчет
        /// </summary>
        /// <param name="date_start"></param>
        /// <param name="date_stop"></param>
        /// <returns></returns>
        public PartialViewResult ReportUnloadBunker(DateTime date_start, DateTime date_stop)
        {
            List<UnloadBunker> list = new List<UnloadBunker>();
            list = this.unb.GetBF9UnloadBunker(date_start, date_stop);
            return PartialView(list);
        }
        #endregion

        #region Отчет о выгрузке материалов
        /// <summary>
        /// Вызвать главную форму
        /// </summary>
        /// <returns></returns>
        public ActionResult UnloadMaterialSmena()
        {
            ViewBag.HierarchyMenu = "HOME:ADD;HOME:BFS2;HOME:BFS2Unload";
            ViewBag.dt = DateTime.Now.Date.ToShortDateString();
            return View();
        }

        public PartialViewResult ReportUnloadMaterialSmena(DateTime date)
        {
            List<UnloadMaterialSmena> list = new List<UnloadMaterialSmena>();
            list = this.unm.GetBF9UnloadMaterialSmena(date);
            if (list == null) return null;
            List<IGrouping<string, UnloadMaterialSmena>> group = list.GroupBy(l => l.Type).ToList();
            return PartialView(group);
        }
        #endregion

    }
}

WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Infrastructure;

namespace WebUI.Controllers
{
    public class HomeController : Controller
    {

        [Access(LogVisit = true)]
        public ActionResult Index()
        {
            return View();
        }

        #region АДД
        /// <summary>
        /// Меню АДД
        /// </summary>
        /// <returns></returns>
        public ActionResult ADD()
        {
            return View();
        }
        /// <summary>
        /// Меню ДЦ-2
        /// </summary>
        /// <returns></returns>
        public ActionResult BFS2()
        {
            ViewBag.HierarchyMenu = "HOME:ADD";
            return View();
        }
        /// <summary>
        /// Меню Загрузка
        /// </summary>
        /// <returns></returns>
        public ActionResult BFS2Unload()
        {
            ViewBag.HierarchyMenu = "HOME:ADD;HOME:BFS2";
            return View();
        }
        /// <summary>
        /// Меню энергоресурсы
        /// </summary>
        /// <returns></returns>
        public ActionResult BFS2Energy()
        {
            ViewBag.HierarchyMenu = "HOME:ADD;HOME:BFS2";
            return View();
        }
        /// <summary>
        /// Меню ДЦ-1
        /// </summary>
        /// <returns></returns>
        public ActionResult BFS1()
        {
            ViewBag.HierarchyMenu = "HOME:ADD";
            return View();
        }
        /// <summary>
        /// Меню энергоресурсы
        /// </summary>
        /// <returns></returns>
        public ActionResult BFS1Energy()
        {
            ViewBag.HierarchyMenu = "HOME:ADD;HOME:BFS1";
            return View();
        }

        #endregion

        #region ЭД
        /// <summary>
        /// Меню ЭД
        /// </summary>
        /// <returns></returns>
        public ActionResult ED()
        {
            return View();
        }
        #endregion

        #region СТО
        /// <summary>
        /// Меню СТО
        /// </summary>
        /// <returns></returns>
        public ActionResult CTO()
        {
            return View();
        }
        /// <summary>
        /// Меню управления энергоэффективности
        /// </summary>
        /// <returns></returns>
        public ActionResult UPEE()
        {
            ViewBag.HierarchyMenu = "HOME:CTO";
            return View();
        }
        /// <summary>
        /// Меню энергоресурсы
        /// </summary>
        /// <returns></returns>
        public ActionResult UPEEEnergy()
        {
            ViewBag.HierarchyMenu = "HOME:CTO;HOME:UPEE";
            return View();
        }

        public ActionResult DATP()
        {
            ViewBag.HierarchyMenu = "HOME:CTO";
            return View();
        }

        public ActionResult DATPUG()
        {
            ViewBag.HierarchyMenu = "HOME:CTO;HOME:DATP";
            return View();
        }

        public ActionResult UGEnergy()
        {
            ViewBag.HierarchyMenu = "HOME:CTO;HOME:DATP;HOME:DATPUG";
            return View();
        }

        #endregion

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        /// <summary>
        /// Отобразить ссылки
        /// </summary>
        /// <param name="list"></param>
        /// <returns></returns>
        public PartialViewResult MenuHierarchy(string list)
        {
            if (list == null) return null;
            return PartialView((object)list);
        }
        /// <summary>
        /// Смена культуры
        /// </summary>
        /// <param name="lang"></param>
        /// <returns></returns>
        public ActionResult ChangeCulture(string lang)
        {
            string returnUrl = Request.UrlReferrer.AbsolutePath;

            List<string> cultures = new List<string>() { "ru", "en", "uk" };
            if (!cultures.Contains(lang))
            {
                lang = "ru";
            }
            // Сохраняем выбранную культуру в куки
            HttpCookie cookie = Request.Cookies["lang"];
            if (cookie != null)
                cookie.Value = lang;   // если куки уже установлено, то обновляем значение
            else
            {
                cookie = new HttpCookie("lang");
                cookie.HttpOnly = false;
                cookie.Value = lang;
                cookie.Expires = DateTime.Now.AddYears(1);
            }
            Response.Cookies.Add(cookie);
            return Redirect(returnUrl);
        }

        [ChildActionOnly]
        public ActionResult Lock()
        {
            return PartialView();
        }
    }
}

WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>
@*<h3>@ViewBag.Message</h3>*@

<p>Web-сайт технологических отчетов</p>

WebUI/Views/Home/BFS1.cshtml
@using WebUI.App_LocalResources;
@{
    ViewBag.Title = @GlobalResource.bfs1_title;
    ViewBag.Section = @GlobalResource.bfs1_section;
    ViewBag.HierarchyMenu = @ViewBag.HierarchyMenu;
    Layout = "~/Views/Shared/_LayoutReportADD.cshtml";
}

<ul class="bmenu">
    <li>@Html.ActionLink(@GlobalResource.report_group_unload, "BFS1Unload", "Home")</li>
    <li>@Html.ActionLink(@GlobalResource.report_group_energy, "BFS1Energy", "Home")</li>
    <li>@Html.ActionLink(@GlobalResource.report_group_tehno, "BFS1Technology", "Home")</li>
</ul>

WebUI/Views/Home/BFS1Energy.cshtml
@using WebUI.App_LocalResources;

@{
    ViewBag.Title = @GlobalResource.bfs1energy_title;
    ViewBag.Section = @GlobalResource.bfs1energy_section;
    ViewBag.HierarchyMenu = @ViewBag.HierarchyMenu;
    Layout = "~/Views/Shared/_LayoutReportADD.cshtml";
}

<ul class="bmenu">
    <li>@Html.ActionLink(@GlobalResource.report_bf9_energy, "EnergySutkiADDForBFS1", "EnergyDay")</li>
</ul>

WebUI/Views/Home/BFS2.cshtml
@using WebUI.App_LocalResources;
@{
    ViewBag.Title = @GlobalResource.bfs2_title;
    ViewBag.Section = @GlobalResource.bfs2_section;
    ViewBag.HierarchyMenu = @ViewBag.HierarchyMenu;
    Layout = "~/Views/Shared/_LayoutReportADD.cshtml";
}

<ul class="bmenu">
    <li>@Html.ActionLink(@GlobalResource.report_group_unload, "BFS2Unload", "Home")</li>
    <li>@Html.ActionLink(@GlobalResource.report_group_energy, "BFS2Energy", "Home")</li>
    <li>@Html.ActionLink(@GlobalResource.report_group_psi, "BFS2PSI", "Home")</li>
    <li>@Html.ActionLink(@GlobalResource.report_group_tehno, "BFS2Technology", "Home")</li>
</ul>

WebUI/Views/Home/BFS2Energy.cshtml
@using WebUI.App_LocalResources;

@{
    ViewBag.Title = @GlobalResource.bfs2energy_title;
    ViewBag.Section = @GlobalResource.bfs2energy_section;
    ViewBag.HierarchyMenu = @ViewBag.HierarchyMenu;
    Layout = "~/Views/Shared/_LayoutReportADD.cshtml";
}

<ul class="bmenu">
    @*<li>@Html.ActionLink(@GlobalResource.report_bf9_energy, "EnergySutkiADDForADD", "EnergyDay")</li>*@
    <li>@Html.ActionLink(@GlobalResource.report_bf9_energy, "EnergySutkiADDForBFS2", "EnergyDay")</li>
</ul>

WebUI/Views/Home/BFS2Unload.cshtml
@using WebUI.App_LocalResources;
@{
    ViewBag.Title = @GlobalResource.bfs2unload_title;
    ViewBag.Section = @GlobalResource.bfs2unload_section;
    ViewBag.HierarchyMenu = @ViewBag.HierarchyMenu;
    Layout = "~/Views/Shared/_LayoutReportADD.cshtml";
}

<ul class="bmenu">
    <li>@Html.ActionLink(@GlobalResource.report_bf9_unload_um, "UnloadMaterialSmena", "BFS2")</li>
    <li>@Html.ActionLink(@GlobalResource.report_bf9_unload_dosing, "DosingMaterial", "BFS2")</li>
    <li>@Html.ActionLink(@GlobalResource.report_bf9_unload_bzu, "UnloadBunker", "BFS2")</li>
</ul>

WebUI/Views/Home/CTO.cshtml
@using WebUI.App_LocalResources;

@{
    ViewBag.Title = @GlobalResource.cto_title;
    ViewBag.Section = @GlobalResource.cto_section;
    Layout = "~/Views/Shared/_LayoutReportCTO.cshtml";
}

<ul class="bmenu">
    <li>@Html.ActionLink(@GlobalResource.menu_report_cto_datp_full, "DATP", "Home")</li>
    <li>@Html.ActionLink(@GlobalResource.menu_report_cto_upee_full, "UPEE", "Home")</li>
</ul>

WebUI/Views/Home/DATP.cshtml
@using WebUI.App_LocalResources;

@{
    ViewBag.Title = @GlobalResource.datp_title;
    ViewBag.Section = @GlobalResource.datp_section;
    ViewBag.HierarchyMenu = @ViewBag.HierarchyMenu;
    Layout = "~/Views/Shared/_LayoutReportDATP.cshtml";
}

<ul class="bmenu">
    <li>@Html.ActionLink(@GlobalResource.menu_report_cto_datp_ug_full, "DATPUG", "Home")</li>
</ul>

WebUI/Views/Home/DATPUG.cshtml
@using WebUI.App_LocalResources;

@{
    ViewBag.Title = @GlobalResource.datpug_title;
    ViewBag.Section = @GlobalResource.datpug_section;
    ViewBag.HierarchyMenu = @ViewBag.HierarchyMenu;
    Layout = "~/Views/Shared/_LayoutReportDATP.cshtml";
}

<ul class="bmenu">
    <li>@Html.ActionLink(@GlobalResource.report_group_energy, "UGEnergy", "Home")</li>
</ul>

WebUI/Views/Home/Index.cshtml
@using WebUI.App_LocalResources;
@{
    Layout = null;
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @Styles.Render("~/Home/css")
    @*<link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow&v1' rel='stylesheet' type='text/css' />
        <link href='http://fonts.googleapis.com/css?family=Wire+One&v1' rel='stylesheet' type='text/css' />*@
</head>
<body>
    <div class="container">
        <h1>@GlobalResource.index_name_webside<span>&nbsp;@GlobalResource.index_name_tehrep</span></h1>

        @*</div>*@
        <ul id="sti-menu" class="sti-menu">

            <li data-hovercolor="#ff395e">
                <a href='@Url.Action("CTO","Home")'>
                    <h2 data-type="mText" class="sti-item">@GlobalResource.index_menu_name_cto</h2>
                    <h3 data-type="sText" class="sti-item">@GlobalResource.index_menu_name_cto_full</h3>
                    <span data-type="icon" class="sti-icon sti-icon-scto sti-item"></span>
                </a>
            </li>
            <li data-hovercolor="#0094FF">
                <a href='@Url.Action("Add","Home")'>
                    <h2 data-type="mText" class="sti-item">@GlobalResource.index_menu_name_add</h2>
                    <h3 data-type="sText" class="sti-item">@GlobalResource.index_menu_name_add_full</h3>
                    <span data-type="icon" class="sti-icon sti-icon-add sti-item"></span>
                </a>
            </li>
            <li data-hovercolor="#ffdd3f">
                <a href="#">
                    <h2 data-type="mText" class="sti-item">@GlobalResource.index_menu_name_sd</h2>
                    <h3 data-type="sText" class="sti-item">@GlobalResource.index_menu_name_sd_full</h3>
                    <span data-type="icon" class="sti-icon sti-icon-sd sti-item"></span>
                </a>
            </li>
            <li data-hovercolor="#57e676">
                <a href="#">
                    <h2 data-type="mText" class="sti-item">@GlobalResource.index_menu_name_rd</h2>
                    <h3 data-type="sText" class="sti-item">@GlobalResource.index_menu_name_rd_full</h3>
                    <span data-type="icon" class="sti-icon sti-icon-rd sti-item"></span>
                </a>
            </li>
            <li data-hovercolor="#d869b2">
                <a href='@Url.Action("ED","Home")'>
                    <h2 data-type="mText" class="sti-item">@GlobalResource.index_menu_name_ed</h2>
                    <h3 data-type="sText" class="sti-item">@GlobalResource.index_menu_name_ed_full</h3>
                    <span data-type="icon" class="sti-icon sti-icon-ed sti-item"></span>
                </a>
            </li>
        </ul>

        <div class="more">
            <ul>

                <li>@GlobalResource.index_mmenu_title</li>
                <li class="selected"><a href="#">@GlobalResource.index_link_go_help_title</a></li>
                <li><a href="#">@GlobalResource.index_link_go_access_title</a></li>
                <li><a href="#">@GlobalResource.index_link_go_admin_title</a></li>
                <li><a href="#">@GlobalResource.index_link_go_about_title</a></li>

            </ul>
        </div>
        <div class="language">
                @using (Html.BeginForm("ChangeCulture", "Home"))
                {
                    @GlobalResource.index_select_lang_title
                    <select length="9" id="countries" name="lang" onchange="$('form').submit();">
                        <option value="ru" @(System.Threading.Thread.CurrentThread.CurrentCulture.Name == "ru-RU" ? "selected" : "")>@GlobalResource.index_select_lang_ru</option>
                        <option value="en" @(System.Threading.Thread.CurrentThread.CurrentCulture.Name == "en-US" ? "selected" : "")>@GlobalResource.index_select_lang_en</option>
                        <option value="uk" @(System.Threading.Thread.CurrentThread.CurrentCulture.Name == "uk-UA" ? "selected" : "")>@GlobalResource.index_select_lang_uk</option>
                    </select>
                }
            </div>
        </div>
        <div class="footer">
            <a href="#"><span> &copy; @DateTime.Now.Year</span> &bull; @GlobalResource.name_developers_section_full</a>
            <span class="right_ab">
                <a href="mailto:Eduard.Levchenko@arcelormittal.com"><strong>@GlobalResource.name_developers_admin</strong></a>
            </span>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-ui")
    @Styles.Render("~/jquery-ui/css")
    @Scripts.Render("~/bundles/easing")
    @Scripts.Render("~/bundles/iconmenu")

    <script type="text/javascript">
        $(function () {
            $('#sti-menu').iconmenu();
        });
    </script>
</body>
</html>

WebUI/Views/Home/Lock.cshtml
<link rel="stylesheet" type="text/css" href="~/Content/lockpanel/lockpanel.css">
<script src="~/Scripts/lockpanel/lockpanel.js"></script>
<div id="lockPanel" class="LockOff"></div>

WebUI/Views/Home/MenuHierarchy.cshtml
@using WebUI.Helpers;
@model String

@foreach (var item in @Model.Split(';'))
{
    string[] link = item.Split(':');
    @Html.ActionLink("-> " + @Html.GetActionMenuTitle((string)link[1]).ToString(), (string)link[1], link[0])
}

WebUI/Views/Home/UPEE.cshtml
@using WebUI.App_LocalResources;

@{
    ViewBag.Title = @GlobalResource.upee_title;
    ViewBag.Section = @GlobalResource.upee_section;
    ViewBag.HierarchyMenu = @ViewBag.HierarchyMenu;
    Layout = "~/Views/Shared/_LayoutReportCTO.cshtml";
}

<ul class="bmenu">
    <li>@Html.ActionLink(@GlobalResource.report_group_energy, "UPEEEnergy", "Home")</li>
</ul>

WebUI/Views/Home/UPEEEnergy.cshtml
@using WebUI.App_LocalResources;

@{
    ViewBag.Title = @GlobalResource.upeeenergy_title;
    ViewBag.Section = @GlobalResource.upeeenergy_section;
    ViewBag.HierarchyMenu = @ViewBag.HierarchyMenu;
    Layout = "~/Views/Shared/_LayoutReportCTO.cshtml";
}

<ul class="bmenu">
    <li>@Html.ActionLink(@GlobalResource.report_add_energy, "EnergySutkiADDForUPEE", "EnergyDay")</li>
</ul>